=== brendayangyang/XmlJsonConvertor/data/students.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/hw4Schema" xmlns:hw4="http://www.example.org/hw4Schema" elementFormDefault="qualified">

    <xs:element name="StudentList" type="hw4:StudentListType"/>

    <xs:complexType name="StudentListType">
        <xs:sequence>
            <xs:element name="Student" type="hw4:StudentType" maxOccurs="unbounded" minOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="StudentType">
        <xs:sequence>
            <xs:element name="SSN" maxOccurs="1" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:pattern value="[0-9]{3}-[0-9]{2}-[0-9]{4}" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="Name" type="xs:string" maxOccurs="1" minOccurs="1" />
            <xs:element name="DOB" type="xs:date" maxOccurs="1" minOccurs="1" />
            <xs:element name="Gender" type="xs:string" maxOccurs="1" minOccurs="1" />
            <xs:element name="Type" type="xs:string" maxOccurs="1" minOccurs="1" />
            <xs:element name="BuildingCode" type="hw4:BuildingCodeListType" maxOccurs="1" minOccurs="1" />
            <xs:element name="Phone" type="hw4:PhoneType" maxOccurs="1" minOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PhoneType">
        <xs:sequence>
            <xs:element name="PhoneNo" maxOccurs="unbounded" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="14" />
                        <xs:minLength value="10" />
                        <xs:pattern value="[0-9]{3}.*" />
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BuildingCodeListType">
        <xs:sequence>
            <xs:element name="OneBuildingCode" type="hw4:BuildingCodeType" maxOccurs="unbounded" minOccurs="0" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="BuildingCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"  />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== brendayangyang/XmlJsonConvertor/data/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<StudentList xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/hw4Schema" xsi:schemaLocation="http://www.example.org/hw4Schema students.xsd">
    <Student>
        <SSN>111-00-1111</SSN>
        <Name>Rylan</Name>
        <DOB>1968-04-01</DOB>
        <Gender>M</Gender>
        <Type>Both</Type>
        <BuildingCode>
            <OneBuildingCode>CFX</OneBuildingCode>
            <OneBuildingCode>JEP</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-1111</PhoneNo>
            <PhoneNo>213-740-1112</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-2222</SSN>
        <Name>Joshua</Name>
        <DOB>1970-04-01</DOB>
        <Gender>M</Gender>
        <Type>Both</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
            <OneBuildingCode>OHE</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-2222</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-3333</SSN>
        <Name>Allen</Name>
        <DOB>1969-04-01</DOB>
        <Gender>F</Gender>
        <Type>Both</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-3333</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-4444</SSN>
        <Name>Aidan</Name>
        <DOB>1985-04-01</DOB>
        <Gender>M</Gender>
        <Type>Both</Type>
        <BuildingCode>
            <OneBuildingCode>JHH</OneBuildingCode>
            <OneBuildingCode>REG</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-4444</PhoneNo>
            <PhoneNo>213-740-4445</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-5555</SSN>
        <Name>Aiden</Name>
        <DOB>1982-04-01</DOB>
        <Gender>M</Gender>
        <Type>Both</Type>
        <BuildingCode>
            <OneBuildingCode>LVY</OneBuildingCode>
            <OneBuildingCode>VKC</OneBuildingCode>
            <OneBuildingCode>WPH</OneBuildingCode>
            <OneBuildingCode>KOH</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-5555</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-6666</SSN>
        <Name>Barak</Name>
        <DOB>1979-04-01</DOB>
        <Gender>F</Gender>
        <Type>Master</Type>
        <BuildingCode></BuildingCode>
        <Phone>
            <PhoneNo>213-740-6666</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-7777</SSN>
        <Name>Basil</Name>
        <DOB>1978-04-01</DOB>
        <Gender>M</Gender>
        <Type>Master</Type>
        <BuildingCode>
            <OneBuildingCode>LVY</OneBuildingCode>
            <OneBuildingCode>VKC</OneBuildingCode>
            <OneBuildingCode>WPH</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-7777</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-8888</SSN>
        <Name>Cayden</Name>
        <DOB>1975-04-01</DOB>
        <Gender>F</Gender>
        <Type>Master</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
            <OneBuildingCode>SAL</OneBuildingCode>
            <OneBuildingCode>OHE</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-8888</PhoneNo>
            <PhoneNo>213-740-8889</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-9999</SSN>
        <Name>BRENDON</Name>
        <DOB>1972-04-01</DOB>
        <Gender>M</Gender>
        <Type>Master</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
            <OneBuildingCode>SAL</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-740-9999</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-00-0000</SSN>
        <Name>Nate</Name>
        <DOB>1973-04-01</DOB>
        <Gender>M</Gender>
        <Type>Master</Type>
        <BuildingCode></BuildingCode>
        <Phone>
            <PhoneNo>213-740-0000</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-1111</SSN>
        <Name>Hannah</Name>
        <DOB>1965-04-01</DOB>
        <Gender>F</Gender>
        <Type>Master</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
            <OneBuildingCode>SAL</OneBuildingCode>
            <OneBuildingCode>OHE</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-1111</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-2222</SSN>
        <Name>Zoe</Name>
        <DOB>1962-04-01</DOB>
        <Gender>F</Gender>
        <Type>Master</Type>
        <BuildingCode>
            <OneBuildingCode>CFX</OneBuildingCode>
            <OneBuildingCode>STU</OneBuildingCode>
            <OneBuildingCode>BKS</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-2222</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-3333</SSN>
        <Name>Alexis</Name>
        <DOB>1963-04-01</DOB>
        <Gender>M</Gender>
        <Type>Phd</Type>
        <BuildingCode></BuildingCode>
        <Phone>
            <PhoneNo>213-741-3333</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-4444</SSN>
        <Name>Madison</Name>
        <DOB>1975-04-01</DOB>
        <Gender>F</Gender>
        <Type>Phd</Type>
        <BuildingCode>
            <OneBuildingCode>KOH</OneBuildingCode>
            <OneBuildingCode>CFX</OneBuildingCode>
            <OneBuildingCode>SAL</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-4444</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-5555</SSN>
        <Name>Adalgisa</Name>
        <DOB>1976-04-01</DOB>
        <Gender>M</Gender>
        <Type>Phd</Type>
        <BuildingCode>
            <OneBuildingCode>CFX</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-5555</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-6666</SSN>
        <Name>Cora</Name>
        <DOB>1977-04-01</DOB>
        <Gender>M</Gender>
        <Type>Phd</Type>
        <BuildingCode>
            <OneBuildingCode>CFX</OneBuildingCode>
            <OneBuildingCode>KOH</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-6666</PhoneNo>
            <PhoneNo>213-741-6667</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-7777</SSN>
        <Name>Adalia</Name>
        <DOB>1982-04-01</DOB>
        <Gender>F</Gender>
        <Type>Phd</Type>
        <BuildingCode></BuildingCode>
        <Phone>
            <PhoneNo>213-741-7777</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-8888</SSN>
        <Name>Ava</Name>
        <DOB>1983-04-01</DOB>
        <Gender>F</Gender>
        <Type>Phd</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
            <OneBuildingCode>OHE</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-8888</PhoneNo>
            <PhoneNo>213-741-8889</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-9999</SSN>
        <Name>Celia</Name>
        <DOB>1986-04-01</DOB>
        <Gender>M</Gender>
        <Type>Phd</Type>
        <BuildingCode>
            <OneBuildingCode>RTH</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-9999</PhoneNo>
        </Phone>
    </Student>

    <Student>
        <SSN>111-11-0000</SSN>
        <Name>Zaida</Name>
        <DOB>1983-04-01</DOB>
        <Gender>F</Gender>
        <Type>Phd</Type>
        <BuildingCode>
            <OneBuildingCode>SAL</OneBuildingCode>
            <OneBuildingCode>EEB</OneBuildingCode>
        </BuildingCode>
        <Phone>
            <PhoneNo>213-741-0000</PhoneNo>
        </Phone>
    </Student>

</StudentList>
